[licenses]
allow = ["Apache-2.0", "MIT", "ISC", "BSD-3-Clause"]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.exceptions]]
name = "unicode-ident"
version = "*"
allow = ["Unicode-3.0"]

[[licenses.exceptions]]
name = "aws-lc-sys"
version = "*"
allow = ["OpenSSL"]
